# syntax - https://github.com/redhat-plumbers-in-action/devel-freezer#policy
---

policy:
  - tags: ['alpha', 'beta']
    feedback:
      frozen-state: |
        🥶 We are currently in ...
        🙏 Please ...
      unfreeze-state: |
        😎 We are no longer in ...

  # Suport for regular expressions
  - tags: ['^v\d*-rc\d$', '^v\d+.\d+.\d+-rc\d$']
    labels:
      allow: ['regression ⚠️']
    feedback:
      frozen-state: |
        > [!IMPORTANT]
        > We are currently in a development freeze phase.
        > Please ...
      unfreeze-state: |
        > [!NOTE]
        > We had successfully released a new major release.
        > We are no longer in a development freeze phase.
