# doc: https://github.com/redhat-plumbers-in-action/devel-freezer#readme
---

name: Development Freezer
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  freezer:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Development Freezer
        uses: jamacku/devel-freezer@fix-tags
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
